name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  backend:
    name: Test & Coverage Back-End
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
      - run: mvn clean verify
      - run: mvn jacoco:report

  frontend:
    name: Test & Coverage Front-End
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run test -- --watch=false --code-coverage

  sonar:
    name: Analyse SonarCloud
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: bobapp
          SONAR_ORGANIZATION: ton_organisation

  docker:
    name: Docker Build & Push
    needs: [sonar]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-backend ./backend
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-frontend ./frontend
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-backend
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-frontend
